#! /bin/bash 
#
#  Bring up/down shake table daemons
#
#  description: 
# The script brings up/down the following programs as user $USER
#
# The isid program allows external users/computers to collect data
# from an ida disk loop.
#
# The q330arch program accepts seed records via socket connection
# and saves them to an ISI disk loop and to an archive directory
# specified in diskloop.config
#
# The ida2liss program allows a LISS feed connection to get any new
# data put on the ISI loop
#
# The netseed program allows rerequest data and supports the ASPseed
# program data requests
#
# The ufors program reads rotation rate data from a serial port
# connected to a uFors-1 rotation rate sensor.  EJZ, EJ1, and EJ2
# define the serial ports for each of the 3 respective channels

PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
RETVAL=0
chanz=00/EJZ
chan1=00/EJ1
chan2=00/EJ2
serz=/dev/ttyS0
ser1=/dev/ttyS1
ser2=/dev/ttyS2
lissz=4000
liss1=4001
liss2=4002
PROG=`basename $0`
SCRIPTPID=$$
numargs=$#

# source configuration file 
. /opt/data/config

# Make sure binaries exists
test -x /opt/data/bin/linux.2.6.i86pc/isid || exit 0
test -x /opt/data/bin/ufors || exit 0
test -x /opt/data/bin/netseed || exit 0
test -x /opt/data/bin/ida2liss || exit 0
test -x /opt/data/bin/q330arch || exit 0

# needs root
# make sure programs can read/write the serial ports
USER=`whoami`
if [[ ${USER} == "root" ]] ; then
  chmod a+rw $serz $ser1 $ser2
fi
echo $USER


# Now start the data collection process
start () {
#
# Make sure isid program is running
#
pid=`/bin/ps h -C isid -o pid,user,cmd | awk '{ print $1 }'`
if [[ "${pid}" == "" ]] ; then
  echo "Starting up isid daemon"
  isid port=39136 log=/opt/data/nrts/log/isid.log -bd
fi

#
# Make sure q330arch program is running
#
pid=`/bin/ps h -C q330arch -o pid,user,cmd | awk '{ print $1 }'`
if [[ "${pid}" == "" ]] ; then
  echo "Starting up q330arch daemon"
  q330arch /etc/q330/DLG1/diskloop.config
fi

#
# Make sure ida2liss program is running
#
port=`/bin/ps h -C ida2liss -o cmd | grep $lissz | awk '{ print $1 }'`
if [[ "${port}" == "" ]] ; then
  echo "Starting up ida2liss $lissz $chanz daemon"
  ida2liss server=localhost isiport=39136 lissport=$lissz log=/opt/data/nrts/log/ida2liss.log depth=640 keepalive=100 raw
fi

pid=`/bin/ps h -C ida2liss -o pid,user,cmd | awk '{ print $1 }'`
port=`/bin/ps h -C ida2liss -o cmd | grep $liss1 | awk '{ print $1 }'`
if [[ "${port}" == "" ]] ; then
  echo "Starting up ida2liss $liss1 $chan1 daemon"
  ida2liss server=localhost isiport=39136 lissport=$liss1 log=/opt/data/nrts/log/ida2liss.log depth=640 keepalive=100 raw
fi

pid=`/bin/ps h -C ida2liss -o pid,user,cmd | awk '{ print $1 }'`
port=`/bin/ps h -C ida2liss -o cmd | grep $liss2 | awk '{ print $1 }'`
if [[ "${port}" == "" ]] ; then
  echo "Starting up ida2liss $liss2 $chan1 daemon"
  ida2liss server=localhost isiport=39136 lissport=$liss2 log=/opt/data/nrts/log/ida2liss.log depth=640 keepalive=100 raw
fi

#
# Make sure netseed daemons are running
#
port=`/bin/ps h -C netseed -o cmd | grep 4003 | awk '{ print $1 }'`
if [[ "${port}" == "" ]] ; then
  echo "Starting up netseed 4003 daemon"
  netseed 4003
fi
port=`/bin/ps h -C netseed -o cmd | grep 4004 | awk '{ print $1 }'`
if [[ "${port}" == "" ]] ; then
  echo "Starting up netseed 4004 daemon"
  netseed 4004
fi

#
# start the ufors programs
#
pid=`/bin/ps h -C ufors -o pid,cmd | grep ${chanz} | awk '{ print $1 }'`
if [[ "${pid}" == "" ]] ; then
  echo "Starting ufors $chanz $serz"
  /opt/data/bin/nice -n -5 ufors /etc/q330/DLG1/diskloop.config $chanz $serz -hz=639.97
  sleep 2
fi

pid=`/bin/ps h -C ufors -o pid,cmd | grep ${chan1} | awk '{ print $1 }'`
if [[ "${pid}" == "" ]] ; then
  echo "Starting ufors $chan1 $ser1"
  /opt/data/bin/nice -n -5 ufors /etc/q330/DLG1/diskloop.config $chan1 $ser1 -hz=639.97
  sleep 2
fi

pid=`/bin/ps h -C ufors -o pid,cmd | grep ${chan2} | awk '{ print $1 }'`
if [[ "${pid}" == "" ]] ; then
  echo "Starting ufors $chan2 $ser2"
  /opt/data/bin/nice -n -5 ufors /etc/q330/DLG1/diskloop.config $chan2 $ser2 -hz=639.97
fi

}


stop ()
{
    echo "Killing shake table daemons" 

    pid=`ps h -C ufors -o pid,cmd | awk '{ print $1 }'`
    if [ "${pid}" != "" ]; then
      echo "Stopping ufors ${pid}"
      kill ${pid}
    fi

    pid=`ps h -C netseed -o pid,cmd | awk '{ print $1 }'`
    if [ "${pid}" != "" ]; then
      echo "Stopping netseed ${pid}"
      kill ${pid}
    fi

    pid=`ps h -C q330arch -o pid,cmd | awk '{ print $1 }'`
    if [ "${pid}" != "" ]; then
      echo "Stopping q330arch ${pid}"
      kill ${pid}
    fi

    pid=`ps h -C ida2liss -o pid,cmd | awk '{ print $1 }'`
    if [ "${pid}" != "" ]; then
      echo "Stopping ida2liss ${pid}"
      kill ${pid}
    fi

    pid=`ps h -C isid -o pid,cmd | awk '{ print $1 }'`
    if [ "${pid}" != "" ]; then
      echo "Stopping isid ${pid}"
      kill ${pid}
    fi

    for i in 1 2 3
    do
       # Per Frank wait two seconds,
       # check if it's still running
       # then send a second kill
       sleep 2;
       pid=`ps h -C isid -o pid,cmd | awk '{ print $1 }'`
       if [ "${pid}" != "" ] ; then
           kill -15 $pid
           echo "Trying again... Killing isid pid $pid"
       else
         continue 3 
       fi
    done
}

echo Execute command $1
case "$1" in

    start)
        start
	;;

    stop)
        stop
	;;

    restart|reload|force-reload)
        echo -n "Restarting $PROG: "
	stop 
        sleep 2
        start
        ;;

    *)
        echo "Usage: /etc/init.d/shake {start|stop|reload|force-reload|restart}"
        exit 1
esac

exit 0
