#!/bin/csh -f
# $Id: CleanEverything,v 1.1.1.1 2000/02/08 20:20:44 dec Exp $

cd ~ida/build/bin
set list = *
foreach platform ($list)
    setenv PLATFORM $platform
    echo $PLATFORM
    cd ~ida/build/src
    make clean
end
