#!/bin/csh -f
# $Id: isiCreateDiskLoops,v 1.1 2008/12/16 18:26:19 dechavez Exp $
#
# Create all ISI and NRTS disk loops

set myname = isiCreateDiskLoops

# General setup

set setup  = ~nrts/scripts/ScriptSetup
if (! -e $setup ) then
    echo "missing $setup"
    goto failure
endif
source $setup

# Command line setup

set error = 0
if ($#argv == 0) then
    set SiteList = "$SystemsList"
else 
    set SiteList = "$argv"
endif

# Loop for each site

foreach site ($SiteList)

    set SiteDir    = $NRTS_HOME/$site

    if (-e $SiteDir/cnf) then
        nrts_mkdl $site
        isimkdl type=ida $site
    else
        isimkdl type=qdp $site
    endif

    mkdir $SiteDir/tee >& /dev/null
end

success:
exit 0

failure:
exit 1

# Revision History
#
# $Log: isiCreateDiskLoops,v $
# Revision 1.1  2008/12/16 18:26:19  dechavez
# initial release
#
# Revision 1.2  2008/12/16 18:18:08  dechavez
# added missing end quote
#
# Revision 1.1  2008/12/16 18:15:22  dechavez
# initial release
#
