#!/bin/csh
# $Id: isp_maketape,v 1.1.1.1 2000/02/08 20:20:44 dec Exp $
 
set tape   = /dev/rmt/0
set tapeN  = /dev/rmt/0n
set rewind = "mt -f $tape rew"
set eject  = "mt -f $tape offl"
set skip   = "mt -f $tapeN fsf"
set dump   = "ufsdump 0unf $tape"
set log    = /etc/backup.log
@ numfiles = 0
 
if (! -e $log) touch $log
 
set filesystems = ""
set filesystems = "$filesystems /dev/rdsk/c1d0s0" # /
set filesystems = "$filesystems /dev/rdsk/c1d0s6" # /usr
set filesystems = "$filesystems /dev/rdsk/c1d0s1" # /var
set filesystems = "$filesystems /dev/rdsk/c1d0s5" # /opt
set filesystems = "$filesystems /dev/rdsk/c1d0s7" # /usr/nrts
 
$rewind
foreach filesystem ($filesystems)
    $rewind
    if ($numfiles > 0) $skip $numfiles
    echo $filesystem >>& $log
    $dump $filesystem >>& $log
    @ numfiles = $numfiles + 1
    echo " " >>& $log
end
 
$eject
 
exit 0

# Revision History
#
# $Log: isp_maketape,v $
# Revision 1.1.1.1  2000/02/08 20:20:44  dec
# import existing IDA/NRTS sources
#
