#!/bin/csh
# $Id: ispIsoNotify,v 1.1 2003/03/18 19:46:44 dechavez Exp $
#
# E-mail notification about completed ISO images

set subject  = "New ISO image ready to burn"
set mail     = "/usr/ucb/mail"
set addr     = IsoNotifyList
set hostname = `hostname`

if ($#argv < 1) then
        set message = "New ISO image ready to burn on host $hostname"
else
        set message = ${hostname}:$argv[1]
endif

echo "$message" | $mail -s "$subject" $addr

# Revision History
#
# $Log: ispIsoNotify,v $
# Revision 1.1  2003/03/18 19:46:44  dechavez
# created
#
