#!/bin/csh -f
#
# $Id: nrts_stop,v 1.1.1.1 2000/02/08 20:20:45 dec Exp $
#
# Stop NRTS 2.0 acquisition

unalias cp rm

if ($#argv < 1) goto help

if ($?NRTS_HOME) then
    set nrts_home = $NRTS_HOME
else
    echo "NRTS_HOME is not defined"
    exit 1
endif

foreach system ($argv)
    @ pid = `nrts_pid $system`
    if ($status == 0 && $pid > 0) kill -TERM $pid
end

exit 0

# Revision History
#
# $Log: nrts_stop,v $
# Revision 1.1.1.1  2000/02/08 20:20:45  dec
# import existing IDA/NRTS sources
#
