#!/bin/csh -f
# $Id: rt593,v 1.1 2008/03/26 22:48:54 dechavez Exp $
#
# Use RT593 config

set debug  = 0

set setup  = ~nrts/scripts/ScriptSetup
if (! -e $setup ) then
    echo "${myname}: missing $setup"
    goto failure
endif
source $setup

set SiteDir = $NRTS_HOME/$DefaultSite
if (! -e $SiteDir) then
	echo "missing $SiteDir"
	exit 1
endif

if (-e $SiteDir/isp) then
	goto ISP
else
	goto ARS
endif

ISP:
cd $SiteDir/isp

foreach runfile (run.rt303 run.rt593)
	if (! -e $runfile) then
		echo "missing $SiteDir/isp/$runfile"
		exit 1
	endif
end

rm -f run
ln -s run.rt593 run
echo "System configured for RT593"

exit 0

ARS:

cd $NRTS_HOME/etc/start

foreach bootfile (boot.rt303 boot.rt593)
	if (! -e $bootfile) then
		echo "missing $NRTS_HOME/etc/start/$bootfile"
		exit 1
	endif
end

rm -f boot
ln -s boot.rtf93 boot
echo "System confgured for RT593"

exit 0
