# $Id: Makefile,v 1.35 2009/03/20 21:17:24 dechavez Exp $
# Make all libraries

all: \
    cssio \
    dbio \
    detect \
    dpm \
    iacp \
    iboot \
    ida \
    ida10 \
    isi \
    isidb \
    isidl \
    iso9660 \
    isp \
    liss \
    logio \
    md5 \
    mio \
    msgq \
    mtio \
    nrts \
    oldmsgq \
    oldmtio \
    oldparo \
    oldttyio \
    paro \
    q330 \
    qdp \
    qdplus \
    sacio \
    sanio \
    sclk \
    seed \
    ttyio \
    udpio \
    util \
    xfer

cssio: FORCE
	cd cssio; $(MAKE)

dbio: FORCE
	cd dbio; $(MAKE)

detect: FORCE
	cd detect; $(MAKE)

dpm: FORCE
	cd dpm; $(MAKE)

iacp: FORCE
	cd iacp; $(MAKE)

iboot: FORCE
	cd iboot; $(MAKE)

ida: FORCE
	cd ida; $(MAKE)

ida10: FORCE
	cd ida10; $(MAKE)

isi: FORCE
	cd isi; $(MAKE)

isidb: FORCE
	cd isidb; $(MAKE)

isidl: FORCE
	cd isidl; $(MAKE)

iso9660: FORCE
	cd iso9660; $(MAKE)

isp: FORCE
	cd isp; $(MAKE)

liss: FORCE
	cd liss; $(MAKE)

logio: FORCE
	cd logio; $(MAKE)

md5: FORCE
	cd md5; $(MAKE)

mio: FORCE
	cd mio; $(MAKE)

modbus: FORCE
	cd modbus; $(MAKE)

msgq: FORCE
	cd msgq; $(MAKE)

mtio: FORCE
	cd mtio; $(MAKE)

nrts: FORCE
	cd nrts; $(MAKE)

oldmsgq: FORCE
	cd oldmsgq; $(MAKE)

oldmtio: FORCE
	cd oldmtio; $(MAKE)

oldparo: FORCE
	cd oldparo; $(MAKE)

oldttyio: FORCE
	cd oldttyio; $(MAKE)

paro: FORCE
	cd paro; $(MAKE)

q330: FORCE
	cd q330; $(MAKE)

qdp: FORCE
	cd qdp; $(MAKE)

qdplus: FORCE
	cd qdplus; $(MAKE)

sacio: FORCE
	cd sacio; $(MAKE)

sanio: FORCE
	cd sanio; $(MAKE)

sclk: FORCE
	cd sclk; $(MAKE)

seed: FORCE
	cd seed; $(MAKE)

ttyio: FORCE
	cd ttyio; $(MAKE)

udpio: FORCE
	cd udpio; $(MAKE)

util: FORCE
	cd util; $(MAKE)

xfer: FORCE
	cd xfer; $(MAKE)

clean: FORCE
	cd cssio;    $(MAKE) $@
	cd dbio;     $(MAKE) $@
	cd detect;   $(MAKE) $@
	cd dpm;      $(MAKE) $@
	cd iacp;     $(MAKE) $@
	cd iboot;    $(MAKE) $@
	cd ida;      $(MAKE) $@
	cd ida10;    $(MAKE) $@
	cd isi;      $(MAKE) $@
	cd isidb;    $(MAKE) $@
	cd isidl;    $(MAKE) $@
	cd iso9660;  $(MAKE) $@
	cd isp;      $(MAKE) $@
	cd liss;     $(MAKE) $@
	cd logio;    $(MAKE) $@
	cd md5;      $(MAKE) $@
	cd mio;      $(MAKE) $@
	cd modbus;   $(MAKE) $@
	cd msgq;     $(MAKE) $@
	cd mtio;     $(MAKE) $@
	cd nrts;     $(MAKE) $@
	cd oldmsgq;  $(MAKE) $@
	cd oldmtio;  $(MAKE) $@
	cd oldparo;  $(MAKE) $@
	cd oldttyio; $(MAKE) $@
	cd paro;     $(MAKE) $@
	cd q330;     $(MAKE) $@
	cd qdp;      $(MAKE) $@
	cd qdplus;   $(MAKE) $@
	cd sacio;    $(MAKE) $@
	cd sanio;    $(MAKE) $@
	cd sclk;     $(MAKE) $@
	cd seed;     $(MAKE) $@
	cd ttyio;    $(MAKE) $@
	cd udpio;    $(MAKE) $@
	cd util;     $(MAKE) $@
	cd xfer;     $(MAKE) $@


remove: FORCE
	cd cssio;    $(MAKE) $@
	cd dbio;     $(MAKE) $@
	cd detect;   $(MAKE) $@
	cd dpm;      $(MAKE) $@
	cd iacp;     $(MAKE) $@
	cd iboot;    $(MAKE) $@
	cd ida;      $(MAKE) $@
	cd ida10;    $(MAKE) $@
	cd isi;      $(MAKE) $@
	cd isidb;    $(MAKE) $@
	cd isidl;    $(MAKE) $@
	cd iso9660;  $(MAKE) $@
	cd isp;      $(MAKE) $@
	cd liss;     $(MAKE) $@
	cd logio;    $(MAKE) $@
	cd md5;      $(MAKE) $@
	cd mio;      $(MAKE) $@
	cd modbus;   $(MAKE) $@
	cd msgq;     $(MAKE) $@
	cd mtio;     $(MAKE) $@
	cd nrts;     $(MAKE) $@
	cd oldmsgq;  $(MAKE) $@
	cd oldmtio;  $(MAKE) $@
	cd oldparo;  $(MAKE) $@
	cd oldttyio; $(MAKE) $@
	cd paro;     $(MAKE) $@
	cd q330;     $(MAKE) $@
	cd qdp;      $(MAKE) $@
	cd qdplus;   $(MAKE) $@
	cd sacio;    $(MAKE) $@
	cd sanio;    $(MAKE) $@
	cd sclk;     $(MAKE) $@
	cd seed;     $(MAKE) $@
	cd ttyio;    $(MAKE) $@
	cd udpio;    $(MAKE) $@
	cd util;     $(MAKE) $@
	cd xfer;     $(MAKE) $@
	rm -rf ../../lib/$(PLATFORM)

REMOVE: FORCE
	cd cssio;    $(MAKE) $@
	cd dbio;     $(MAKE) $@
	cd detect;   $(MAKE) $@
	cd dpm;      $(MAKE) $@
	cd iacp;     $(MAKE) $@
	cd iboot;    $(MAKE) $@
	cd ida;      $(MAKE) $@
	cd ida10;    $(MAKE) $@
	cd isi;      $(MAKE) $@
	cd isidb;    $(MAKE) $@
	cd isidl;    $(MAKE) $@
	cd iso9660;  $(MAKE) $@
	cd isp;      $(MAKE) $@
	cd liss;     $(MAKE) $@
	cd logio;    $(MAKE) $@
	cd md5;      $(MAKE) $@
	cd mio;      $(MAKE) $@
	cd modbus;   $(MAKE) $@
	cd msgq;     $(MAKE) $@
	cd mtio;     $(MAKE) $@
	cd nrts;     $(MAKE) $@
	cd oldmsgq;  $(MAKE) $@
	cd oldmtio;  $(MAKE) $@
	cd oldparo;  $(MAKE) $@
	cd oldttyio; $(MAKE) $@
	cd paro;     $(MAKE) $@
	cd q330;     $(MAKE) $@
	cd qdp;      $(MAKE) $@
	cd qdplus;   $(MAKE) $@
	cd sacio;    $(MAKE) $@
	cd sanio;    $(MAKE) $@
	cd sclk;     $(MAKE) $@
	cd seed;     $(MAKE) $@
	cd ttyio;    $(MAKE) $@
	cd udpio;    $(MAKE) $@
	cd util;     $(MAKE) $@
	cd xfer;     $(MAKE) $@
	rm -rf ../../lib/$(PLATFORM)
FORCE:
