#!/bin/csh -f
# $Id: nrts_tipars,v 1.1.1.1 2000/02/08 20:20:45 dec Exp $

set host = `uname -n`
setenv NRTS_HOME ~nrts

set platformrc = $NRTS_HOME/.platform
if ( -e $platformrc ) then
    source $platformrc
else
    echo "error: missing $platformrc"
    exit 1
endif

set path = ($NRTS_HOME/bin/$platform $NRTS_HOME/scripts /usr/local/bin $path)
if ( -e /usr/local/bin/kermit) then
    set kermit = /usr/local/bin/kermit
else
    echo "missing /usr/local/bin/kermit"
    exit 1
endif

clear
$kermit -l /dev/ttyS1 -b 9600 -c
if ($status == 0) clear

exit 0

# Revision History
#
# $Log: nrts_tipars,v $
# Revision 1.1.1.1  2000/02/08 20:20:45  dec
# import existing IDA/NRTS sources
#
