#!/usr/bin/perl
#=========================================================================
# Script: newser330
#
# Purpose: Updates the serial number in seneca.config so a new Q330
#          can be put through SATQ testing
#
#=========================================================================

use strict;

my $newserno;
my $cmd;
my $cmdout;

# Make sure the first four non optional arguments are present
if ($#ARGV != 0)
{

  print "Invalid number of arguments\n";

  print
"Utility to change the Q330 serial number in seneca.config\n" .
"\n" .
"Usage:\n" .
"   newser330 <serno>\n";
}

# pull mandatory arguments
# convert to upper case first
tr/a-z/A-Z/ for @ARGV;

$newserno = $ARGV[0];

$cmd = "cd /etc/q330/DLG1 ; Seneca << end\n" .
       "y\n" .
       "c\n" .
         "a\n" .
           "$newserno\n" .
         "c\n" .
           "SATQ\n" .
         "s\n" .
         "x\n" .
       "q\n" .
       "end\n";

$cmdout = `$cmd`
  or die "Seneca update failed\n";

system("terminate q330serv; sleep 10") == 0
  or die "Failed to run 'terminate q330serv': $?\n";

system("q330serv /etc/q330/DLG1") == 0
  or die "Failed to run 'q330serv /etc/q330/DLG1': $?\n";

exit(0);
