#!/bin/sh
#
# start/stop NRTS processes
#
# $Id: nrts,v 1.2 2005/09/29 17:42:21 dechavez Exp $

case "$1" in
'start')

    NRTSRC="/usr/nrts/etc/start/boot"
    if [ -f ${NRTSRC} ]; then
        echo "Starting NRTS"
        csh ${NRTSRC} > /dev/null &
    fi
    ;;
        
'stop')
    echo "Stopping NRTS"
    pkill -TERM -x AlphaSend
    pkill -TERM -x drmd
    pkill -TERM -x isid
    pkill -TERM -x isidl
    pkill -TERM -x ispd
    pkill -TERM -x nrts_alpha
    pkill -TERM -x nrts_edes
    pkill -TERM -x nrts_wrtdl
    ;;
*)
    echo "Usage: /etc/init.d/nrts { start | stop }"
    ;;
esac
