#! /bin/bash 
#
#  Bring up/down dispstatus program
#
#  description: 
# The dispstatus program sends error messages to an attached
# console.

PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
RETVAL=0
PROG=`basename $0`
numargs=$#
MAXWAIT=10

# source configuration file 
. /home/maint/config 

# Make sure binary exists
if [ ! -x /usr/local/sbin/dispstatus ] 
then
    echo "Error: Executable missing! Exiting..."
    exit 0 
fi

if [ `whoami` == "root" ]
then
  chmod 666 /dev/ttyS3
fi


# Now start the program 
start () {

    echo "Starting $PROG..." 
    dispstatus /dev/ttyS3
}


stop ()
{
    pid=`/bin/ps -A -o pid,cmd | awk '{ if ($2 == "dispstatus") print $1 }'`
    echo "Killing $PROG ${pid}" 
    while [[ ${pid} != "" ]]
    do
        kill ${pid}
        sleep 1
        pid=`/bin/ps -A -o pid,cmd | awk '{ if ($2 == "dispstatus") print $1 }'`
        if [ $MAXWAIT -le 1 ] ; then
          exit
        else
          MAXWAIT=`expr $MAXWAIT - 1`
        fi
    done
}

case "$1" in

    start)
        start
	;;

    stop)
        stop
	;;

    restart|reload|force-reload)
        echo -n "Restarting $PROG: "
	stop 
        sleep 2
        start
        ;;

    *)
        echo "Usage: /etc/init.d/$PROG {start|stop|reload|force-reload|restart}"
        exit 1
esac

exit 0
