#! /bin/bash
#
#  Bring up/down ida2liss daemon
#  ida2liss creates a liss server connection on the slate, 
#  which allows access from the liss server
#


PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
RETVAL=0
PROG=`basename $0`
SCRIPT_PID=$$
numargs=$#

# Make sure binary exists
test -x /usr/local/sbin/ida2liss || exit 0

# If the config file doesn't exist, then exit
if [ ! -f /etc/q330/ida2liss.config ]; then    
    echo "ida2liss: Config file doesn't exist... exiting."
    exit 0
fi

# Source config file
. /etc/q330/ida2liss.config


filtercmd ()
{
  if [[ $# > 0 ]] ; then
    findraw=`echo "$*" | grep raw`
    if [ "${findraw}" == "" ] ; then
      RAW="raw"
    else
      RAW=""
    fi

    if test -z "$FILTER" ; then
      ida2liss $RAW server=localhost isiport=$ISIPORT lissport=$* log=$IDA2LISS_LOG depth=$IDA2LISS_DEPTH keepalive=$IDA2LISS_KEEPALIVE
    else
      ida2liss $RAW server=localhost isiport=$ISIPORT lissport=$* log=$IDA2LISS_LOG depth=$IDA2LISS_DEPTH filter=$FILTER keepalive=$IDA2LISS_KEEPALIVE
    fi
  fi
}

# Now start the data collection process
start () 
{
    filtercmd $LISSPORT
    filtercmd $LISSPORT1
    filtercmd $LISSPORT2
    filtercmd $LISSPORT3
    filtercmd $LISSPORT4
    filtercmd $LISSPORT5
    filtercmd $LISSPORT6
    filtercmd $LISSPORT7
    filtercmd $LISSPORT8
    filtercmd $LISSPORT9
}



stop ()
{
    if [ $numargs -lt 2 ]
    then
        pid=`/bin/ps -A -o comm,pid | grep -e "^$PROG " | grep -v $SCRIPT_PID | awk '{ print $2 }'`
        if [[ "$pid" == "" ]] ; then
           echo "No $PROG process to stop"
        else
           echo "Killing $PROG $pid"
           kill $pid
        fi
    else
        shift
        args="$*"
        for arg in $args
        do
          pid=`/bin/ps -A -o comm,pid,cmd | grep -e "^$PROG " | grep -v $SCRIPT_PID | grep $arg | awk '{ print $2 }'`
          if [[ "$pid" == "" ]] ; then
             echo "No $PROG $arg process to stop"
          else
             echo "Killing $PROG $arg"
             kill $pid
          fi
        done
    fi
}

case "$1" in

    start)
        start
        ;;

    stop)
        stop $*
        ;;

    restart|reload|force-reload)
        echo -n "Restarting $PROG: "
        stop 
        sleep 2
        start
        ;;

    *)
        echo "Usage: /etc/init.d/ida2liss {start|stop|reload|force-reload|restart}"
        exit 1
esac

exit 0
