#! /bin/bash
#
#  Bring up/down netseed 
#
#  description: 
#  The netseed daemon supports netreq protocol and ASPseed data requests
#  26 April 2011 -- Support for /etc/q330/netseed.config file
#                   to allow multiple instances of netseed to listen
#                   at different ports.  Used for relay server
#
#  config: /etc/q330/diskloop.config  and /etc/q330/netseed.config
#          if /etc/q330/netseed.config does not exist, use 4004 for port
#  logfile: /var/log/netreq.log

PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
RETVAL=0
PROG=`basename $0`
SCRIPT_PID=$$
numargs=$#
 
# Make sure binary exists
test -x /usr/local/sbin/netseed || exit 0

if [ ! -f /etc/q330/netseed.config ]; then
  REQPORT1=4004
else
  # Source config file
  . /etc/q330/netseed.config
fi

runport ()
{
  if [[ $# > 0 ]] ; then
    /usr/local/sbin/netseed $*
    echo "Starting netseed $*"
  fi
}

start ()
{

  runport $REQPORT1
  runport $REQPORT2
  runport $REQPORT3
  runport $REQPORT4
  runport $REQPORT5
  runport $REQPORT6
  runport $REQPORT7
  runport $REQPORT8
  runport $REQPORT9
}


stop ()
{
    if [ $numargs -lt 2 ]
    then
        pid=`/bin/ps -A -o comm,pid | grep -e "^$PROG " | grep -v $SCRIPT_PID |
awk '{ print $2 }'`
        if [[ "$pid" == "" ]] ; then
           echo "No $PROG process to stop"
        else
           echo "Killing $PROG $pid"
           kill $pid
        fi
    else
        shift
        args="$*"
        for arg in $args
        do
          pid=`/bin/ps -A -o comm,pid,cmd | grep -e "^$PROG " | grep -v $SCRIPT_PID | grep $arg | awk '{ print $2 }'`
          if [[ "$pid" == "" ]] ; then
             echo "No $PROG $arg process to stop"
          else
             echo "Killing $PROG $arg"
             kill $pid
          fi
        done
    fi

}

case "$1" in

    start)
        start
	;;

    stop)
        stop $*
	;;

    restart|reload|force-reload)
        echo -n "Restarting netseed "
	stop 
	sleep 2
        start
	;;

    *)
        echo "Usage: /etc/init.d/netseed {start|stop|reload|force-reload|restart}"
        exit 1
esac

exit 0
