#! /bin/bash
#
#  Bring up/down ida2liss daemon
#  ida2liss creates a liss server connection on the slate, 
#  which allows access from the liss server
#


PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
RETVAL=0
PROG=`basename $0`
numargs=$#


# Make sure binary exists
test -x /usr/local/sbin/ida2liss || exit 0

# If the config file doesn't exist, then exit
if [ ! -f /etc/q330/ida2liss.config ]; then    
    echo "ida2liss: Config file doesn't exist... exiting."
    exit 0
fi

# Source config file
. /etc/q330/ida2liss.config



# Now start the data collection process
start () 
{
    echo "Starting $PROG..." 
    IDA2LISS="ida2liss server=localhost isiport=$ISIPORT lissport=$LISSPORT log=$IDA2LISS_LOG depth=$IDA2LISS_DEPTH filter=$FILTER keepalive=$IDA2LISS_KEEPALIVE raw"
    logger $IDA2LISS
    ` $IDA2LISS `
    #ida2liss server=localhost isiport=$ISIPORT lissport=$LISSPORT log=$IDA2LISS_LOG depth=$IDA2LISS_DEPTH filter=$FILTER keepalive=$IDA2LISS_KEEPALIVE raw
}



stop ()
{
    echo "Killing $PROG ..." 
    pids=`pidof $PROG`
    if [ -n "$pids" ] ; then
        killall $PROG 
        if [ $? != 0 ]; then
            echo "Error stopping $PROG.."
        fi  
    fi
    echo
}

case "$1" in

    start)
        start
        ;;

    stop)
        stop
        ;;

    restart|reload|force-reload)
        echo -n "Restarting $PROG: "
        stop 
        sleep 2
        start
        ;;

    *)
        echo "Usage: /etc/init.d/isid {start|stop|reload|force-reload|restart}"
        exit 1
esac

exit 0
