PLATFORM = $(shell uname)

CC = gcc -g

LIB330_DIR=../lib330
COPT =
LIBS = -lm -lpthread
CFLAGS = -Wall -B static -I. -I$(LIB330_DIR)

# Platform Magic
ifeq ($(PLATFORM), SunOS)
    LIBS += -lsocket
endif

SRCS = ocfdump.c dump_hex.c jio.c record.c simclist.c tokens.c
OBJS = $(SRCS:%.c=%.o)

all: ocfdump

ocfdump: $(OBJS)
	$(CC) $(OBJS) $(LIB330_DIR)/lib330.a $(LIBS) -o $@

